version: "2"
run:
  go: "1.26"
  allow-parallel-runners: true
linters:
  default: standard
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
