# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: spelunk

builds:
  - id: spelunk-darwin
    skip: '{{ ne .Env.TARGET_OS "darwin" }}'
    dir: cmd/spelunk
    main: .
    binary: spelunk
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.name={{.ProjectName}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.version={{.Version}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.commit={{.ShortCommit}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.branch={{.Branch}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.date={{.Date}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.builtBy=goreleaser'

  - id: spelunk-linux
    skip: '{{ ne .Env.TARGET_OS "linux" }}'
    dir: cmd/spelunk
    main: .
    binary: spelunk
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CC_linux_amd64=gcc
      - CC_linux_arm64=aarch64-linux-gnu-gcc
      - CC={{ index .Env (print "CC_" .Os "_" .Arch) }}
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.name={{.ProjectName}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.version={{.Version}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.commit={{.ShortCommit}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.branch={{.Branch}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.date={{.Date}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.builtBy=goreleaser'

  - id: spelunk-windows
    skip: '{{ ne .Env.TARGET_OS "windows" }}'
    dir: cmd/spelunk
    main: .
    binary: spelunk
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.name={{.ProjectName}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.version={{.Version}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.commit={{.ShortCommit}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.branch={{.Branch}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.date={{.Date}}'
        -X 'github.com/detro/spelunk/cmd/spelunk/internal/cli.builtBy=goreleaser'

source:
  enabled: false

archives:
  - formats:
      - binary
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Env.TARGET_OS }}_checksums.txt"
  algorithm: sha512

signs:
  - id: cosign-checksums
    artifacts: checksum
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
  - id: cosign-binaries
    artifacts: binary
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
  - id: gpg-checksums
    artifacts: checksum
    cmd: gpg
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  disable: true

release:
  github:
    owner: detro
    name: spelunk
  mode: keep-existing
  draft: true
  name_template: "{{ .Tag }}"
  prerelease: auto
  make_latest: auto

