# See: https://taskfile.dev/docs/getting-started
version: '3'

env:
  GOBIN: '{{.TASKFILE_DIR}}/bin'

tasks:
  generate:
    cmd: go generate ./...

  build:
    deps: [generate]
    cmd: go build .

  test:
    deps: [test.full]

  test.short:
    cmd: go test -v -race -cover -short {{.CLI_ARGS | default "./..."}}

  test.full:
    cmd: go test -v -race -cover {{.CLI_ARGS | default "./..."}}

  test.ci:
    cmd: go test -v -race -coverprofile=coverage.out -covermode=atomic {{.CLI_ARGS | default "./..."}}

  lint:
    cmd: golangci-lint run --allow-parallel-runners --verbose

  vuln:
    desc: Run govulncheck for vulnerability scanning
    cmd: govulncheck ./...

  lint-fix:
    cmd: golangci-lint run --fix --allow-parallel-runners --verbose

  fmt:
    cmd: golangci-lint fmt -v

  run:
    cmd: go run . {{.CLI_ARGS}}

  mod.update:
    cmd: go get -t -u ./...

  mod.tidy:
    cmd: go mod tidy -v

  dependencies.update:
    deps:
      - mod.update
      - mod.tidy

  tools.plugins:
    desc: Install all necessary asdf plugins
    cmd: |
      # Install all plugins listed in .tool-versions (will fail but continue for out-of-registry ones)
      cut -d' ' -f1 .tool-versions | while read -r plugin; do
        asdf plugin add "$plugin" || true
      done
      # Install out-of-registry plugins
      asdf plugin add govulncheck https://github.com/wizzardich/asdf-govulncheck.git

  tools.update:
    desc: Update all tools in .tool-versions to latest available versions via asdf
    deps:
      - tools.plugins
    cmd: |
        cut -d' ' -f1 .tool-versions | while read -r plugin; do
          asdf set "$plugin" latest || true
        done

  tools.install:
    desc: Install all tools in .tool-versions via asdf
    deps:
      - tools.plugins
    cmd: asdf install

  doc.serve:
    cmds:
      - go install golang.org/x/pkgsite/cmd/pkgsite@latest
      - echo "Opening http://localhost:8080/github.com/detro/spelunk"
      - sleep 2 && open http://localhost:8080/github.com/detro/spelunk &
      - bin/pkgsite
