# See: https://taskfile.dev/docs/getting-started
version: '3'

env:
  GOBIN: '{{.TASKFILE_DIR}}/bin'

tasks:
  generate:
    cmd: go generate ./...

  build:
    deps: [generate]
    cmd: go build .

  test:
    deps: [test.full]

  test.short:
    cmd: go test -v -race -cover -short ./...

  test.full:
    cmd: go test -v -race -cover ./...

  lint:
    cmd: golangci-lint run --allow-parallel-runners --verbose

  lint-fix:
    cmd: golangci-lint run --fix --allow-parallel-runners --verbose

  fmt:
    cmd: golangci-lint fmt -v

  run:
    cmd: go run . {{.CLI_ARGS}}

  mod.update:
    cmd: go get -t -u ./...

  mod.tidy:
    cmd: go mod tidy -v

  update-dependencies:
    deps:
      - mod.update
      - mod.tidy

  readme:
    cmd: glow -t README.md

  doc.serve:
    cmds:
      - go install golang.org/x/pkgsite/cmd/pkgsite@latest
      - echo "Opening http://localhost:8080/github.com/detro/spelunk"
      - sleep 2 && open http://localhost:8080/github.com/detro/spelunk &
      - bin/pkgsite
