# See: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Release Spelunk CLI

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - 'cmd/spelunk/v*'

jobs:
  release:
    name: Release Spelunk CLI (${{ matrix.target_os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: macos-latest
            target_os: darwin
          - os: windows-latest
            target_os: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: .tool-versions

      - name: Install ARM64 Cross Compiler
        if: matrix.target_os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set Release Environment
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME#cmd/spelunk/}"
          echo "GORELEASER_CURRENT_TAG=${TAG}" >> "$GITHUB_ENV"
          echo "TARGET_OS=${{ matrix.target_os }}" >> "$GITHUB_ENV"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.2

      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
